---
permalink: legal-notices.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Avisos legales de NetApp Workload Factory para EDA
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Los avisos legales proporcionan acceso a declaraciones de derechos de autor, marcas comerciales, patentes y más.



== Derechos de autor

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marcas comerciales

NETAPP, el logotipo de NETAPP y las marcas enumeradas en la página de Marcas comerciales de NetApp son marcas comerciales de NetApp, Inc. Otros nombres de empresas y productos pueden ser marcas comerciales de sus respectivos propietarios.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Patentes

Puede encontrar una lista actualizada de las patentes propiedad de NetApp en:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Política de privacidad

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



== Código abierto

Los archivos de aviso proporcionan información sobre derechos de autor y licencias de terceros utilizados en el software de NetApp .

https://docs.netapp.com/us-en/workload-family/media/workload-factory-notice.pdf["NetApp Workload Factory"^]
