---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, Workload Factory, builders, Workload Factory, EDA, electronic design automation' 
summary: Descubra las novedades de Workload Factory para EDA. 
---
= Novedades de NetApp Workload Factory para EDA
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Conozca las novedades sobre la capacidad EDA de Workload Factory.



== 4 de enero de 2026



=== NetApp Workload Factory para desarrolladores ahora NetApp Workload Factory para EDA

Workload Factory para constructores ahora es Workload Factory para EDA. El cambio de nombre refleja el enfoque en las cargas de trabajo de automatización de diseño electrónico (EDA).

Workload Factory para EDA le ayuda a optimizar FSx para ONTAP en múltiples sistemas de archivos. Puede optimizar el rendimiento y reducir los costos operativos automatizando los parámetros de almacenamiento, analizando las restricciones de rendimiento y obteniendo información sobre los proyectos de EDA. Workload Factory para EDA está diseñado para integrarse con sus marcos de infraestructura como código (IaC).



=== Integración de la página de inicio del asistente de IA de Ask Me

La página de inicio de la consola Workload Factory incorpora el asistente de IA Ask me, que le permite hacer preguntas sobre su propio almacenamiento, obtener información personalizada directamente de su entorno y consultar conversaciones anteriores. Puede interactuar con Pregúnteme para comprender sus cargas de trabajo, solucionar problemas y obtener más información sobre Workload Factory, todo sin salir de la consola.



== 5 de octubre de 2025



=== BlueXP workload factory ahora NetApp Workload Factory

BlueXP ha sido renombrado y rediseñado para reflejar mejor el papel que desempeña en la gestión de su infraestructura de datos. Como resultado, la BlueXP workload factory pasó a llamarse NetApp Workload Factory.



== 16 de junio de 2025



=== Soporte para clones

Ahora puedes clonar un proyecto en BlueXP Workload Factory for Builders. Cuando clonas un proyecto, Builders crea un nuevo proyecto a partir de una instantánea, con la misma configuración que el original. La clonación es útil para crear rápidamente proyectos similares o para realizar pruebas. Puedes montar el nuevo clon del proyecto siguiendo las instrucciones en Builders.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["Administrar versiones de proyectos de BlueXP Workload Factory for Builders"]



== 4 de mayo de 2025



=== Terminología de permisos actualizada

La interfaz de usuario y la documentación de Workload Factory ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos automatizados.



== 1 de diciembre de 2024



=== Versión inicial de la carga de trabajo de los constructores

BlueXP Workload Factory for Builders simplifica el acceso y el consumo de versiones de software, eliminando la necesidad de herramientas o scripts personalizados. Le permite consumir versiones de software como clones instantáneos integrados con Perforce Helix Core como un espacio de trabajo conveniente para sus procesos de desarrollo, ahorrando tiempo y recursos.

La versión inicial incluye la capacidad de administrar proyectos y espacios de trabajo, y automatizar acciones con Codebox. También puedes integrar Builders con Perforce Helix Core, para que puedas administrar diferentes versiones de cada proyecto y cambiar entre ellas rápidamente.
